[package]
name = "proj_phase1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
# Used for prime factoring
prime_factorization = "1.0.4"
imp = "0.1.0"
