[package]
name = "hangman"
version = "1.0.0"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"
rand = "0.8.5"
